USE aprovechamiento_energia;

-- INSERTAR VALORES EN LA TABLA DEPARTAMENTOS
INSERT INTO departamentos (nombre_departamento, codigo_departamento) VALUES 
('Cesar', 20), 
('Tolima', 73), 
('Córdoba', 23), 
('Atlántico', 8), 
('Bolívar', 13), 
('Caquetá', 18), 
('Casanare', 85), 
('Cauca', 19), 
('Cundinamarca', 25), 
('Huila', 41), 
('La Guajira', 44), 
('Magdalena', 47), 
('Meta', 50), 
('Norte de Santander', 54), 
('Santander', 68), 
('Valle del Cauca', 76), 
('Arauca', 81), 
('Amazonas', 91), 
('Antioquia', 5), 
('Chocó', 27), 
('Guaviare', 95), 
('Nariño', 52), 
('Putumayo', 86), 
('Sucre', 70), 
('Vaupés', 97), 
('Vichada', 99), 
('Boyacá', 15), 
('Caldas', 17), 
('Quindío', 63), 
('Risaralda', 66), 
('San Andrés y Providencia Y Santa Catalina', 88), 
('Guainía', 94);

-- COMPROBAR ENTRADAS A LA TABLA DEPARTAMENTOS
SELECT * FROM departamentos;

-- INSERTAR DATOS EN LA TABLA GRUPO CULTIVO
INSERT INTO grupo_cultivo (grupo_cultivo) VALUES
('Cereales'),
('Frutales'),
('Tuberculos y platanos'),
('Otros permanentes'),
('Oleaginosas'),
('Cultivos tropicales tradicionales');

-- COMPROBAR DATOS TABLA GRUPO CULTIVO
SELECT * FROM grupo_cultivo;

INSERT INTO tipo_operacion (nombre_tipo_operacion) VALUES
('Hidráulica'),
('Solar'),
('Térmica');

-- COMPROBAR VALORES TIPO OPERACION
SELECT * FROM tipo_operacion;

-- INSERTAR NOMBRE OPERADOR
INSERT INTO operador (nombre_operador) VALUES 
('HZ ENERGY S.A.S. E.S.P.'),
('EMPRESAS PUBLICAS DE MEDELLIN E.S.P.'),
('VATIA S.A. E.S.P.'),
('EMPRESAS PUBLICAS DE CALARCA ESP'),
('P.CH EL COCUYO SAS ESP'),
('SIGMA2 COMERCIALIZADORA DE ENERGIA ELECTRICA SAS ESP'), 
('HIDROTOLIMA S.A. E.S.P.'),
('SPECTRUM RENOVAVEIS S.A.S. E.S.P.'),
('COMPAÑÍA INTEGRAL ENERGETICA S.A.S E.S.P'),
('FUENTES DE ENERGIAS RENOVABLES S.A.S. E.S.P.'),
('EMPRESA DE GENERACION Y PROMOCION DE ENERGIA DE ANTIOQUIA S.A. E.S.P.'),
('GENERADORA Y COMERCIALIZADORA DE ENERGIA DEL CARIBE S.A. E.S.P.'),
('PROELECTRICA S.A.S E.S.P.'), 
('ENERGIA DEL RIO PIEDRAS S.A. E.S.P'),
('GENERADORA ALEJANDRIA S.A.S. E.S.P.'), 
('CELSIA COLOMBIA S.A. E.S.P.'),
('AURES BAJO S.A.S. E.S.P.'),
('ISAGEN S.A. E.S.P.'),
('EMPRESA DE ENERGIA DE PEREIRA S.A. E.S.P.'),
('SANTA FE ENERGY ZOMAC S.A.S. E.S.P.'),
('ENEL COLOMBIA SA E.S.P.'),
('EMPRESA MUNICIPAL DE ENERGIA ELECTRICA S.A. E.S.P.'),
('ENERGETICA S.A. E.S.P.'),
('ENERCO S.A. E.S.P.'),
('ENERGIA RENOVABLE DE COLOMBIA S.A.S E.S.P.'),
('HIDROELECTRICA BARRANCAS SAS E.S.P.'),
('ELECTRIFICADORA DEL HUILA S.A. E.S.P.'),
('HIDROENERGIA DE LA MONTAÑA S.A.S E.S.P'), 
('IAC ENERGY S.A.S. E.S.P.'),
('CENTRAL HIDROELÉCTRICA CONCORDIA S.A.S. E.S.P.'),
('RISARALDA ENERGIA S.A.S. E.S.P.'),
('ENERGIA DEL SUROESTE S.A. E.S.P.'),
('PCH SAN BARTOLOME S.A.S. E.S.P. '),
('EMPRESA GENERADORA Y COMERCIALIZADORA DE ENERGIA ELECTRICA DE COLOMBIA S.A. E.S.P.'),
('CENTRALES ELECTRICAS DE NARIÑO S.A. E.S.P.'),
('COMPANIA DE ELECTRICIDAD DE TULUA S.A. E.S.P.'),
('ESPACIO PRODUCTIVO S.A.S. E.S.P.'),
('CEMEX ENERGY S.A.S E.S.P.'),
('AES COLOMBIA & CIA. S.C.A. E.S.P.'),
('CENTRAL HIDROELÉCTRICA ZEUS SAS ESP'),
('HIDROELECTRICA DEL ALTO PORCE S.A.S. E.S.P.'),
('EMPRESA URRA S.A. E.S.P.'),
('UNERGY ENERGY DIGITAL S.A.S E.S.P'),
('ERCO GENERACION S.A.S. ESP'),
('ENERGIA LIMPIA Y EFICIENTE S.A.S ESP'),
('GREENYELLOW COMERCIALIZADORA S.A.S. E.S.P.'),
('ELECTRIFICADORA DEL META S.A. E.S.P.'),
('NITRO ENERGY COLOMBIA S.A.S. E.S.P.'),
('ENERGIA Y GAS DE COLOMBIA SAS ESP'),
('DUCK ENERGY S.A.S. E.S.P.'),
('FOTOVOLTAICO EL YARUMO SAS ESP'),
('SOL DE LAS CIÉNAGAS S.A.S. E.S.P.'), 
('SPK LA MATA S.A.S E.S.P'),
('SPK LA UNIÓN S.A.S. E.S.P.'), 
('PARQUE SOLAR PORTON DEL SOL SAS E.S.P.'),
('GENERSOL S.A.S. E.S.P.'), 
('DEPI ENERGY S.A.S. E.S.P.'),
('COMERCIALIZADORA 4G ENERGIA SAS E.S.P.'), 
('BCCY CORDOBA S.A.S. E.S.P.'),
('GENERSA S.A.S. E.S.P.'), 
('TERMOPIEDRAS S.A. E.S.P.'),
('DRUMMOND POWER S.A.S. E.S.P.'), 
('BIOGAS COLOMBIA S.A.S. E.S.P '),
('PROYECTOS ENERGETICOS DEL CAUCA S.A. E.S.P.'),
('VOLTAJE EMPRESARIAL S.A.S. E.S.P.'), 
('TERMO MECHERO MORRO S.A.S E.S.P '),
('RIOPAILA ENERGÍA S.A.S. E.S.P. '),
('TERMOBARRANQUILLA S.A. EMPRESA DE SERVICIOS PUBLICOS'),
('ENFRAGEN TERMOFLORES S.A.S. E.S.P.'), 
('GESTION ENERGETICA S.A. E.S.P.'),
('COMPAÑÍA ELÉCTRICA DE SOCHAGOTA  S.A. E.S.P.'),
('TERMOTASAJERO S.A. E.S.P.'), 
('TERMOTASAJERO DOS S.A. E.S.P. '),
('TERMOCANDELARIA S.A.S. - E.S.P. '), 
('TERMO CARIBE S.A.S. E.S.P.'),
('GENERADORA TERMOCENTRO S.A.S. E.S.P.'),
('TERMOEMCALI I S.A. E.S.P.'),
('TERMONORTE S.A.S. E.S.P.'),
('ENFRAGEN TERMOVALLE S.A.S. EMPRESA DE SERVICIOS PUBLICOS'),
('TERMOYOPAL GENERACION 2 S.A.S E.S.P.');

-- COMPROBAR VALORES OPERADORES
SELECT * FROM operador;











